import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Highlights</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <img src='/assets/logo.svg'/>
        <h1>The FIRST Streaming App to Watch Sports Highlights.  </h1>
        <p>Stop wasting time searching for Sports Highlights. Watch everything in the new Highlights App. </p>
        <div>
          <img src='/assets/mob1.svg'/>
          <img src='/assets/mob2.svg'/>
        </div>
        <p className={styles.small_text}>Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. </p>
      </main>

      <div className={styles.account_box}>
        <h3>Create your account</h3>
        <label for="first_name">First name</label>
        <input id="first_name" type="text" placeholder="Enter your first name" name="first_name"/>

        <label for="last_name">Last name</label>
        <input id="last_name" type="text" placeholder="Enter your last name" name="last_name"/>

        <label for="email_address">Email</label>
        <input id="email_address" type="email" placeholder="Enter a valid email address" name="email_address"/>

        <label for="password">Password</label>
        <input id="password" type="password" placeholder="Enter a 8 digital password" name="password"/>

        <label for="birth">Date of birth</label>
        <input id="birth" type="date" value="" name="birth"/>
        <p className={styles.tyc}><b>Terms & Conditions</b><br/><br/>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. </p>
        <button className={styles.register_button}>REGISTER</button>
        <button className={styles.login_button}>SIGN IN TO YOUR ACCOUNT</button>
      </div>
      <p className={styles.small_text_footer}>Copyright 2021®   |    Link 1   |   Link 2 <br/><br/>Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. </p>
    </div>
  )
}
